### ISSUE TITLE
Bringing the API to Patch 0.8.16

### ISSUE THREAD

**Issue by Tri125** [GwentAPI/data#2]
http://wpc.4d7d.edgecastcdn.net/004D7D/mkt/document/Patch-EN.pdf

I currently don't have access to the game so I was only able to change what was clearly stated in the patch note like changes to buff/debuff, attacks, and rarity in commit 18e98ac7a0d9417990888ac46c56b7214298bbff .

I will have to verify any changes to the text of the cards within the game.

**Comment by Darkmessage** [comment]
Hey, since I got some time to waste in a few hours, I'll be updating the cards.
