### ISSUE TITLE
Is there any plan for supporting multiple languages?

### ISSUE THREAD

**Issue by davePlug** [GwentAPI/data#5]
I know the game is translated in multiple languages, do you have any plan on including the data for different languages or documenting how to extract the data in the same format you did?

**Comment by Tri125** [comment]
Yes, there are plans to include the different localization, it's my current priority. I should have a draft of the new API specs by the end of the week or the one after. After that, it will be all about updating my db population script.

**Comment by davePlug** [comment]
Hi @Tri125, Any update on this? Is there any way i can help with the db population scripts ( are they on some repo? )

**Comment by Tri125** [comment]
Sadly, no there's nothing concrete yet but I've begun certain steps like rewriting the db_init script in Go. I'll forward you to this issue https://github.com/GwentAPI/gwentapi/issues/19 and I'd like us to continue discussing it on that one that way we don't have to keep track of multiple projects for the same request.

A few weeks ago I quickly put together some documents: https://github.com/GwentAPI/gwentapi/blob/master/README.md. The last paragraph should be what you are looking for ;)

I'll be closing this issue so we can discuss this further on the main project.
